# Ref:
# - `../../source/templates/application.yaml` file
# - https://github.com/metalwhale/ocean/blob/main/kubernetes/inventory/group_vars/k8s_cluster/k8s-net-cilium.yml

# Doc: https://docs.cilium.io/en/v1.18/network/l2-announcements/
l2announcements:
  # Enable l2 announcement from cilium to replace Metallb
  enabled: true
# Doc: https://docs.cilium.io/en/v1.18/network/kubernetes/kubeproxy-free/
kubeProxyReplacement: true
# Doc: https://docs.cilium.io/en/v1.18/network/servicemesh/gateway-api/gateway-api/#installation
# Remember to restart `deployment/cilium-operator` and `ds/cilium` to enable Cilium Gateway API Controller
gatewayAPI:
  enabled: true
